language: node_js
node_js:
- node
cache: npm
script:
- npm run build
- npm run test:unit
deploy:
  provider: heroku
  api_key:
    secure: Ku6REwDnCvBMPPMBxoGQJcKl4lf0AsCaTj6pZqjwKJgfMCNwrjnXbZTTpUGqqdX+fh1z4e+sPFbk9yAGpsglA0v6tXjC/gl+tR7JIBAXYUXXtpsRiwLtFaTslvTqg0A8EqI2aTLuJPQE4W9tRH53S0yA5JamQoQbTgrF6lh9LPrxn4WT8SSwrp14oGIyTxZAXfv+sB7UgKk+hV/3UN7+/shr2CfO3bqrDb+x64Nt8egt8I7HsWYPQrKE4isszn2+vqRQSojgjRtmpN6nh+TIQjDnYf2HuCHLf56cyTq9DUdDsCBh4uTTwfOSwT8YdTFeAbjqmLolSssqIXI5NQTHOqSn72QRcy7up3ojocabiPUvBeU/4Lvs6NXAohm1IAVcMzEY3hCORN97ICGJzqW+cQHqJIxkXWnxWVztgMCfPV1F6dj9RcmHXmK36nVCKaavLhymxgY5HdnSdqR71debqOdbp9PSN5rGDHWKh6rPSpj792L+8vFRkLysILDMh1PlN0ZIJgxavC3kbXri3cCOmUSwJD4Cp7i1phuBZKOOLEDSbuBdk/q+qypY24ZYq+qwNS/qvSsrznTU2Lib3yzJLo2e2r9rNX9XcThb0gsjVgFRR6NHNEtDjilYTUsELAQRarLXPGrVpabuh+Q+7xbdw2bumgFDPFPTMxeFsTDy1dw=
  app: stormy-eyrie-32485
  on:
    repo: Asceryx/timemanagerFront
    branch: develop
  skip_cleanup: 'true'
